# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101stnNF56LHwjkZT1F27mj7S04PHFm5U
"""

import math

# Data points
points = {
    'A': (2,3),
    'B': (3,4),
    'C': (6,6),
    'D': (7,7)
}

# Initial centroids
centroid1 = points['A']
centroid2 = points['C']

def distance(p1, p2):
    return math.sqrt((p1[0]-p2[0])**2 + (p1[1]-p2[1])**2)

iteration = 1

while True:
    cluster1 = []
    cluster2 = []

    print(f"\nIteration {iteration}")

    # Assign points to nearest centroid
    for name, point in points.items():
        d1 = distance(point, centroid1)
        d2 = distance(point, centroid2)

        if d1 < d2:
            cluster1.append(point)
            print(f"{name} -> Cluster 1")
        else:
            cluster2.append(point)
            print(f"{name} -> Cluster 2")

    # Calculate new centroids
    def mean(cluster):
        x = sum(p[0] for p in cluster) / len(cluster)
        y = sum(p[1] for p in cluster) / len(cluster)
        return (x, y)

    new_centroid1 = mean(cluster1)
    new_centroid2 = mean(cluster2)

    print("New Centroid 1:", new_centroid1)
    print("New Centroid 2:", new_centroid2)

    # Stop if centroids do not change
    if new_centroid1 == centroid1 and new_centroid2 == centroid2:
        break

    centroid1 = new_centroid1
    centroid2 = new_centroid2
    iteration += 1

print("\nFinal Clusters:")
print("Cluster 1:", cluster1)
print("Cluster 2:", cluster2)

import numpy as np

data = np.array([2,4,10,12,3,20,30,11,25])
c1, c2 = 2, 20   # initial centroids

while True:
    c1_points = [x for x in data if abs(x-c1) <= abs(x-c2)]
    c2_points = [x for x in data if abs(x-c1) > abs(x-c2)]

    new_c1 = np.mean(c1_points)
    new_c2 = np.mean(c2_points)

    if new_c1 == c1 and new_c2 == c2:
        break

    c1, c2 = new_c1, new_c2

print("Cluster 1:", c1_points, "Centroid:", c1)
print("Cluster 2:", c2_points, "Centroid:", c2)